on:
  push:
    branches: 
      - main
jobs:
  test-and-build:
    name: Run flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"
          cache: true
      - name: Get Dependencies
        run: flutter pub get
      # - name: Test App
      #   run: flutter test
      - name: Build APK
        run: flutter build apk --split-per-abi
      # - name: Make Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release
      #     path: build/app/outputs/apk/release/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/apk/release/app-arm64-v8a-release.apk
      
    
